# Shows the Sponsor button on the repo and profile.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: jmcombs
# Uncomment after creating the account:
# ko_fi: your-kofi-username
